### ISSUE TITLE
Question about hsrb_gazebo_launch

### ISSUE THREAD

**Issue by lmeee** [ShigemichiMatsuzaki/my_dotfiles#1]
Hi, I notices that you include package relating with HSR in your .bashrc. I am also trying to use HSR in Gazebo, but I have a problem about the package named hsrb_gazebo_launch. I am using Ubuntu 16.04 and ROS Kinetic. 

If I just do 'sudo apt-get install ros-kinetic-hsrb-gazebo-launch', I will find nothing. Also, I checked ROS Kinetic repository at 'http://repositories.ros.org/status_page/ros_kinetic_default.html' and there was no package named hsrb_gazebo_launch. I wonder where and how to get this ROS package.

I really appreciate it if you can help me out. Thank you for your patience and I am looking forward to your reply.

**Comment by ShigemichiMatsuzaki** [comment]
Hi @lmeee 

`hsrb_gazebo_launch` is not included in the kinetic repository, but in the repository provided by tmc (Toyota Motor Corporation).
If you have been registered as a member of HSR community, please log in the portal site and follow the instruction (https://docs.hsr.io/hsr_develop_manual_en/start_development/simulator.html)

**Comment by lmeee** [comment]
Thank you for your reply! It helps a lot.

Currently I don't have an account and I guess I need to work on that.
